[package]
name = "dbml-draw"
version = "0.1.0"
edition = "2021"

[dependencies]
dbml-rs = "1.0.0"
svg = "0.17"
clap = { version = "4", features = ["derive"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.8"
thiserror = "2"
